language: python
python:
  - "3.6.3"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
env:
  matrix:
  - PYMATGEN_VERSION=2017.9.1
  - PYMATGEN_VERSION=2018.1.19
  - PYMATGEN_VERSION=2019.1.13
  - PYMATGEN_VERSION=2019.7.30
before_install:
  - pip install --upgrade pip coverage codecov
  - pip install pymatgen==$PYMATGEN_VERSION
install:
  - pip install .
# command to run tests
script:
  - cd tests && cd auto_test && coverage run -m unittest && cd ../data &&  coverage run -m unittest && cd ../generator && coverage run -m unittest && cd ../database && coverage run -m unittest  && cd ../.. && coverage combine tests/*/.coverage && coverage report --include=dpgen/*
after_success:
  - codecov
